### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by liam-lemonade** [Kuuuube/unterp#1]
ie. please write a readme!

Interpolation at the same rate of the tablet doesn't make sense to me. You're interpolating what data? Interpolation is to provide "faux-inputs" inbetween real inputs, so what does this do?

**Comment by Kuuuube** [comment]
As I have outlined already in the repo with `Popular OpenTabletDriver interpolator filters with interpolation removed.`, there is no interpolation occurring in the modified filters.

The filters that have been modified are not solely for interpolating. Hawku Smoothing applies smoothing and interp normally but without the interp it's just smoothing. Similarly, Devocub AntiChatter applies antichatter and interp, BezierInterp applies smoothing and interp, SpringInterp applies a spring physics simulation and interp. By removing interp from any of these, we are not left with nothing, we are left with the base filtering they offer.

If I had taken, for example, a linear interpolator and removed the interpolation it would indeed do nothing.

I may add something additional to the documentation later. I just whipped this up in <20 mins because someone happened to remind me about it.
